server:
  port: 10001
spring:
  application:
    name: C-Auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.46.128:3306/auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wereiyou
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.46.128:8848
uaa:
  jwt:
    sign-key: cauth